### ISSUE TITLE
ASL 2.0 and GPL are incompatible

### ISSUE THREAD

**Issue by trixpan** [phishme/jssdeep#1]
Hi,

Just as a heads up, I noticed the ssdeep implemtation is licensed GPL 2, while your overall code is ASL 2. 

AFAIK those two licenses are not compatible.

**Comment by rufrancis** [comment]
Andre,

I have reached out to Jesse Kornblum and have changed the license of the project to GPLv2 at his request.  Thanks for pointing out the issue and keeping everyone honest.

Kind Regards,
Russ

--
Russell Francis
Senior Developer
Phone: +1 (216) 220-4222
Web: http://phishme.com/
